vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "ms-azuretools.vscode-docker"
    - "esbenp.prettier-vscode"
    - "mhutchie.git-graph"
    - "eamodio.gitlens"
    - "johnsoncodehk.volar"

tasks:
  - init: docker-compose build
  - command: |
      docker-compose up -d
