/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, Cat } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";

export class CatServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CatFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatFindManyArgs>
  ): Promise<number> {
    return this.prisma.cat.count(args);
  }

  async findMany<T extends Prisma.CatFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatFindManyArgs>
  ): Promise<PaginatedInterface<Cat>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.cat.findMany(args),
      this.prisma.cat.count(),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.CatFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatFindUniqueArgs>
  ): Promise<Cat | null> {
    return this.prisma.cat.findUnique(args);
  }
  async create<T extends Prisma.CatCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatCreateArgs>
  ): Promise<Cat> {
    return this.prisma.cat.create<T>(args);
  }
  async update<T extends Prisma.CatUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatUpdateArgs>
  ): Promise<Cat> {
    return this.prisma.cat.update<T>(args);
  }
  async delete<T extends Prisma.CatDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatDeleteArgs>
  ): Promise<Cat> {
    return this.prisma.cat.delete(args);
  }
}
